server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /health {
        access_log off;
        return 200 '{"status":"ok","workspace":"desafio","demanda":"1010"}\n';
        add_header Content-Type application/json;
    }
}
